sonar.projectKey=telco-churn-mlops
sonar.projectName=TelcoChurn
sonar.language=py
sonar.sources=src/,serving/
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/venv/**,**/tests/**
sonar.python.version=3.12
