apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telcochurn

resources:
  - namespace.yaml
  - model-api.yaml
  - minio.yaml
  - redis.yaml
  - mlflow.yaml
  - postgres.yaml
  - prometheus.yaml
  - prometheus-rbac.yaml
  - prometheus-config.yaml
  - grafana.yaml
  - grafana-datasources.yaml
  - grafana-dashboards.yaml
  - airflow.yaml
  - airflow-dags.yaml
  - otel-collector.yaml
  - otel-collector-config.yaml
  - tempo.yaml
  - tempo-config.yaml
  - kyverno/require-prometheus-annotation.yaml
  - kyverno/require-resource-limits.yaml
  - kyverno/disallow-latest-tag.yaml
